version: "3.9"
services:
  web:
    build: frontend
    ports:
      - "3001:3001"
    env_file:
      - frontend/.env
    links:
      - middleware
  middleware:
    build: middleware
    ports:
      - "8080:8080"
    links:
      - ml_decision_server
    environment:
      - ML_SERVER_URL=http://ml_decision_server:5000
      - MENTOR_URL=http://protectddos:5001
    networks:
      - backend
  ml_decision_server:
    image: sulasdelii/risk_classifier:latest
    expose:
      - "5000"
    networks:
      - backend
  ml_models_management:
    image: bentoml/yatai-service:latest
    command:
      - --db-url=${DB_URL}
      - --repo-base-url=${REPO_BASE_URL}
    volumes:
      - ${BENTO_HOME}:/bentoml
    ports:
      - "50051:50051"
      - "3000:3000"
  protectddos:
    image: sulasdelii/protectddos:latest
    expose:
      - "5001"
    networks:
      - backend
networks:
  backend: