version: "3.9"
services:
  middleware:
    build: middleware
    ports:
      - "8080:8080"
    links:
      - ml_decision_server
    networks:
      - backend
  ml_decision_server:
    build: ml_decision_server/build
    expose:
      - "5000"
    networks:
      - backend
networks:
  backend: